### ISSUE TITLE
Incorrect setting in master-pipeline.yml

### ISSUE THREAD

**Issue by terrenceferguson** [sumitraj0103/Letsdevops#6]
I was following your tutorial from YouTube (great job by the way!), and I kept running into an issue not being able to access "BuildType" in my build template that was being pased down from the master-pipeline.yml. After investigation (and a lot of trial and error), I discovered that the initial parameter pass was wrong:

https://github.com/sumitraj0103/Letsdevops/blob/e694f3299df8ca561026b3f65173c7125bee6492/ADOYAML/yaml-template/master-pipeline.yml#L28

This should be:
```yaml
${{ parameters.buildtype }}
```
I can do a PR to change it if you'd like, I just wanted to let you know since I'm sure lots of people are following your example like I did.

Thanks!

**Comment by sumitraj0103** [comment]
I have modified it. Thanks for pointing out
